In [5]:
import pandas as pd
pd.__version__

'1.3.5'

In [2]:
import json
import pickle
import numpy as np
import pandas as pd
import collections
from tqdm import tqdm

import warnings
warnings.filterwarnings('ignore')

In [31]:
input_len = 144
df = pd.read_csv("train_data.csv")
df = df.fillna(0)

In [3]:
## drop abnormal samples
def drop_abnormal(df_train):
    index_list1 = []
    ls = list(df_train['Patv_seq'])
    for i in range(len(ls)):
        n = len([x for x in ls[i] if x<0])
        if n>100:
            index_list1.append(i)

    index_list2 = []
    ls = list(df_train['Pab1_seq'])
    for i in range(len(ls)):
        n = len([x for x in ls[i] if x>89])
        if n>100:
            index_list2.append(i)

    abnormal = list(set(index_list1)|set(index_list2))
    ls_new = []
    for x in range(len(df_train)):
        if x not in abnormal:
            ls_new.append(x)
            
    return df_train.loc[ls_new]

In [ ]:
for turbid in range(134): 
    print(turbid)
    full_dict = collections.defaultdict(list)
    turb_data = df[df['TurbID']==turbid+1].reset_index(drop=True)
    ls = list(turb_data['Patv'])
    for i in range(0, len(ls)-288-input_len):
        full_dict['Wspd_seq'].append(list(turb_data['Wspd'])[i:i+input_len])
        full_dict['Patv_seq'].append(list(turb_data['Patv'])[i:i+input_len])
        full_dict['Etmp_seq'].append(list(turb_data['Etmp'])[i:i+input_len])
        full_dict['Itmp_seq'].append(list( turb_data['Itmp'])[i:i+input_len])
        full_dict['Pab1_seq'].append(list(turb_data['Pab1'])[i:i+input_len])      

        full_dict['target'].append(list(turb_data['Patv'])[i+input_len:i+input_len+288])

    df_his = pd.DataFrame(full_dict)
    df_his.to_csv('data/turbine_data'+str(turbid+1)+'.csv', index=False)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133

In [4]:
a = pd.read_csv('data/turbine_data134.csv')

In [7]:
34848/144

242.0

In [9]:
a

,Wspd_seq,Patv_seq,Etmp_seq,Itmp_seq,Pab1_seq,target
0,"[0.0, 4.85, 4.33, 4.25, 4.22, 4.46, 4.29, 4.3,...","[0.0, 275.66, 267.17, 256.78, 246.74, 252.36, ...","[0.0, 30.83, 30.79, 30.77, 30.72, 30.64, 30.56...","[0.0, 30.59, 30.58, 30.5, 30.49, 30.48, 30.38,...","[0.0, 0.23, 0.03, 0.04, 0.02, 0.02, 0.02, 0.02...","[965.69, 1135.45, 1173.53, 954.39, 753.69, 572..."
1,"[4.85, 4.33, 4.25, 4.22, 4.46, 4.29, 4.3, 3.74...","[275.66, 267.17, 256.78, 246.74, 252.36, 248.4...","[30.83, 30.79, 30.77, 30.72, 30.64, 30.56, 30....","[30.59, 30.58, 30.5, 30.49, 30.48, 30.38, 30.2...","[0.23, 0.03, 0.04, 0.02, 0.02, 0.02, 0.02, 0.0...","[1135.45, 1173.53, 954.39, 753.69, 572.11, 347..."
2,"[4.33, 4.25, 4.22, 4.46, 4.29, 4.3, 3.74, 3.86...","[267.17, 256.78, 246.74, 252.36, 248.46, 235.6...","[30.79, 30.77, 30.72, 30.64, 30.56, 30.47, 30....","[30.58, 30.5, 30.49, 30.48, 30.38, 30.29, 30.4...","[0.03, 0.04, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0...","[1173.53, 954.39, 753.69, 572.11, 347.32, 250...."
3,"[4.25, 4.22, 4.46, 4.29, 4.3, 3.74, 3.86, 4.39...","[256.78, 246.74, 252.36, 248.46, 235.68, 211.4...","[30.77, 30.72, 30.64, 30.56, 30.47, 30.53, 30....","[30.5, 30.49, 30.48, 30.38, 30.29, 30.41, 31.4...","[0.04, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0...","[954.39, 753.69, 572.11, 347.32, 250.64, 169.5..."
4,"[4.22, 4.46, 4.29, 4.3, 3.74, 3.86, 4.39, 4.37...","[246.74, 252.36, 248.46, 235.68, 211.48, 196.6...","[30.72, 30.64, 30.56, 30.47, 30.53, 30.99, 30....","[30.49, 30.48, 30.38, 30.29, 30.41, 31.48, 30....","[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0...","[753.69, 572.11, 347.32, 250.64, 169.58, 16.23..."
...,...,...,...,...,...,...
28363,"[1.24, 1.16, 1.56, 0.0, 1.36, 1.46, 1.72, 1.87...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[13.04, 13.08, 13.14, 0.0, 13.34, 13.35, 13.41...","[15.78, 15.7, 15.69, 0.0, 15.52, 15.7, 15.52, ...","[90.38, 90.38, 90.38, 0.0, 90.38, 90.38, 90.38...","[1519.64, 1519.59, 1519.57, 1519.6, 1519.57, 1..."
28364,"[1.16, 1.56, 0.0, 1.36, 1.46, 1.72, 1.87, 2.8,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 114.9...","[13.08, 13.14, 0.0, 13.34, 13.35, 13.41, 13.48...","[15.7, 15.69, 0.0, 15.52, 15.7, 15.52, 15.47, ...","[90.38, 90.38, 0.0, 90.38, 90.38, 90.38, 90.38...","[1519.59, 1519.57, 1519.6, 1519.57, 1351.26, 1..."
28365,"[1.56, 0.0, 1.36, 1.46, 1.72, 1.87, 2.8, 3.27,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 114.99, 12...","[13.14, 0.0, 13.34, 13.35, 13.41, 13.48, 13.42...","[15.69, 0.0, 15.52, 15.7, 15.52, 15.47, 15.14,...","[90.38, 0.0, 90.38, 90.38, 90.38, 90.38, 90.09...","[1519.57, 1519.6, 1519.57, 1351.26, 1241.45, 1..."
28366,"[0.0, 1.36, 1.46, 1.72, 1.87, 2.8, 3.27, 2.98,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 114.99, 121.35,...","[0.0, 13.34, 13.35, 13.41, 13.48, 13.42, 14.41...","[0.0, 15.52, 15.7, 15.52, 15.47, 15.14, 15.58,...","[0.0, 90.38, 90.38, 90.38, 90.38, 90.09, 2.79,...","[1519.6, 1519.57, 1351.26, 1241.45, 1511.15, 1..."
28367,"[1.36, 1.46, 1.72, 1.87, 2.8, 3.27, 2.98, 2.76...","[0.0, 0.0, 0.0, 0.0, 0.0, 114.99, 121.35, 88.1...","[13.34, 13.35, 13.41, 13.48, 13.42, 14.41, 16....","[15.52, 15.7, 15.52, 15.47, 15.14, 15.58, 16.8...","[90.38, 90.38, 90.38, 90.38, 90.09, 2.79, 0.05...","[1519.57, 1351.26, 1241.45, 1511.15, 1517.9, 1..."

In [10]:
import ast
b = ast.literal_eval(a['Wspd_seq'][134])
print(len(b))

144

In [14]:
b

[9.0,
 7.81,
 5.44,
 6.72,
 8.6,
 7.44,
 7.35,
 7.07,
 7.13,
 7.29,
 8.16,
 8.87,
 8.89,
 7.9,
 6.97,
 6.23,
 4.91,
 4.45,
 3.77,
 1.69,
 1.09,
 1.44,
 1.28,
 0.71,
 0.66,
 0.72,
 0.43,
 0.6,
 0.79,
 0.57,
 0.77,
 1.71,
 4.13,
 3.21,
 2.83,
 2.16,
 1.94,
 2.26,
 1.9,
 1.67,
 1.98,
 2.94,
 2.43,
 1.77,
 2.13,
 2.91,
 2.17,
 2.59,
 1.49,
 1.31,
 2.16,
 1.69,
 1.17,
 1.83,
 2.12,
 2.52,
 1.99,
 1.73,
 1.16,
 0.96,
 1.9,
 1.61,
 1.07,
 1.12,
 1.12,
 0.84,
 1.19,
 1.23,
 1.08,
 1.06,
 1.14,
 0.8,
 0.97,
 0.98,
 1.11,
 1.14,
 1.69,
 4.24,
 3.97,
 5.13,
 3.42,
 5.35,
 3.34,
 4.38,
 3.78,
 4.42,
 4.07,
 4.28,
 3.04,
 3.77,
 3.64,
 2.35,
 3.78,
 2.78,
 2.83,
 3.57,
 1.73,
 2.79,
 3.5,
 2.94,
 2.86,
 2.47,
 3.08,
 3.0,
 3.56,
 2.44,
 1.71,
 1.38,
 2.16,
 2.85,
 1.7,
 3.87,
 2.91,
 3.78,
 2.76,
 3.63,
 4.45,
 3.83,
 3.77,
 3.73,
 4.56,
 4.87,
 3.94,
 3.71,
 4.78,
 4.26,
 4.89,
 3.71,
 4.18,
 4.46,
 3.91,
 3.96,
 3.73,
 3.0,
 2.14,
 1.93,
 2.2,
 1.99,
 3.3,
 3.15,
 7.18,
 8.47,
 8.29,
 8.51]

In [15]:
len(a)

28368

In [21]:
df_loc = pd.read_csv('turb_location.CSV')

dist_dict = {}
for i in tqdm(range(134)):
    x = float(df_loc[df_loc['TurbID']==i+1]['x'])
    y = float(df_loc[df_loc['TurbID']==i+1]['y'])
    df_loc['dist'] = np.sqrt((df_loc['x']-x)**2+(df_loc['y']-y)**2)
    dist_dict[i+1] = list(df_loc.sort_values('dist', ascending=True)['TurbID'])[1:]

100%|████████████████████████████████████████████████████████████████████████████████| 134/134 [00:00<00:00, 733.43it/s]

In [22]:
dist_dict[134]

[113,
 133,
 114,
 132,
 112,
 91,
 111,
 92,
 115,
 131,
 93,
 110,
 130,
 116,
 94,
 71,
 109,
 72,
 70,
 73,
 69,
 95,
 117,
 108,
 74,
 129,
 90,
 75,
 89,
 96,
 107,
 118,
 128,
 76,
 88,
 106,
 97,
 3,
 119,
 127,
 2,
 4,
 1,
 77,
 87,
 5,
 24,
 6,
 98,
 105,
 23,
 120,
 126,
 78,
 86,
 22,
 7,
 99,
 21,
 104,
 8,
 79,
 121,
 125,
 85,
 27,
 29,
 26,
 25,
 28,
 30,
 20,
 103,
 100,
 47,
 84,
 124,
 122,
 46,
 19,
 45,
 101,
 102,
 83,
 44,
 9,
 123,
 18,
 50,
 49,
 51,
 31,
 43,
 10,
 52,
 68,
 48,
 17,
 82,
 32,
 67,
 42,
 53,
 11,
 66,
 33,
 16,
 81,
 54,
 65,
 41,
 12,
 55,
 64,
 15,
 34,
 40,
 80,
 56,
 63,
 35,
 39,
 14,
 57,
 62,
 38,
 13,
 61,
 37,
 60,
 36,
 59,
 58]

In [23]:
df_loc.sort_values('dist',ascending=True)

     TurbID          x           y         dist
133     134    11.3385  6713.46517     0.000000
112     113     9.6374  7189.28109   475.818961
132     133    78.4309  6231.32903   486.781930
113     114    41.4225  7662.24037   949.252036
131     132    62.6774  5749.90633   964.925552
..      ...        ...         ...          ...
36       37  4306.2330   473.27282  7575.362653
59       60  5287.3353  1181.28512  7644.681703
35       36  4303.7037     0.00000  7968.375844
58       59  5285.9086   707.18265  7993.529849
57       58  5279.4781   231.50508  8352.790040

[134 rows x 4 columns]

In [33]:
df_group = df[['Day','Tmstamp','Patv']].groupby(['Day','Tmstamp'], as_index=False).agg(list)
df_group.columns = ['Day','Tmstamp','Patv_list']

In [34]:
with open('data/dist_dict.pickle', 'wb') as f:
    pickle.dump(dist_dict, f)

In [37]:
for i in tqdm(range(134)):
    df_tmp = pd.read_csv('data/turbine_data'+str(i+1)+'.csv')
    df_tmp['index'] = list(range(len(df_tmp)))
    df_tmp = df_tmp.sample(frac=0.01, random_state=2)
    index_list = list(df_tmp['index'])
    df_tmp['TurbID'] = i+1

    turb_data = df[df['TurbID']==i+1].reset_index(drop=True)
    near_turbs = dist_dict[i+1][:121]
    index_new = [x+144-1 for x in index_list]
    selected_df = turb_data.loc[index_new]
    selected_df = pd.merge(selected_df, df_group, how='left', on=['Day','Tmstamp'])
    selected_df['Patv_space'] = selected_df['Patv_list'].apply(lambda x: [x[k-1] for k in near_turbs])    
    df_tmp['Patv_space'] = list(selected_df['Patv_space'])
    
    
    if i==0:
        train = df_tmp.copy()
    else:
        train = pd.concat([train, df_tmp])
train = train.reset_index(drop=True)
train = train.sample(frac=1, random_state=2).reset_index(drop=True)

100%|█████████████████████████████████████████████████████████████████████████████████| 134/134 [03:45<00:00,  1.68s/it]

In [38]:
cols = [x for x in train.columns if 'seq' in x or x=='target']
for col in cols:
    train[col] = train[col].apply(lambda x: json.loads(x))
    
train = drop_abnormal(train)
train.to_csv('data/train_data42.csv', index=False)

In [42]:
dat42 = pd.read_csv('data/train_data42.csv')
print(dat42)

                                                Wspd_seq  \
0      [0.29, 0.59, 0.97, 1.38, 1.94, 2.23, 2.54, 1.8...
1      [1.62, 1.15, 1.84, 2.42, 1.72, 1.75, 1.75, 2.9...
2      [2.67, 2.75, 2.65, 2.66, 2.42, 2.31, 2.04, 2.1...
3      [11.25, 10.66, 10.63, 9.57, 10.14, 9.93, 9.13,...
4      [4.52, 3.73, 3.6, 3.49, 3.03, 2.82, 3.56, 3.54...
...                                                  ...
37044  [7.07, 7.26, 7.55, 7.57, 7.72, 7.71, 7.05, 7.1...
37045  [3.25, 2.18, 2.09, 1.97, 2.17, 2.37, 2.16, 1.4...
37046  [1.84, 3.88, 4.39, 3.72, 3.91, 3.86, 4.47, 2.9...
37047  [6.32, 5.96, 6.11, 5.59, 5.0, 5.12, 5.3, 5.9, ...
37048  [6.67, 5.74, 6.91, 5.13, 4.51, 6.54, 6.37, 5.6...

                                                Patv_seq  \
0      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20.31, 86....
2      [110.84, 111.16, 103.88, 96.08, 87.81, 88.23, ...
3      [1033.06, 1039.58, 1302.54, 1262.94, 1350.97, ...
4      [232.71, 152.88, 132.2, 118.21, 53.07, 69.46, ...
...                                                  ...
37044  [755.06, 742.34, 790.33, 773.86, 791.98, 703.8...
37045  [107.14, 31.96, 35.2, 37.22, 52.73, 50.69, 41....
37046  [0.0, 67.83, 217.08, 150.25, 163.84, 167.28, 2...
37047  [650.06, 490.62, 500.19, 466.35, 355.16, 377.4...
37048  [0.0, 0.0, 0.0, 82.56, 133.23, 363.76, 398.75,...

                                                Etmp_seq  \
0      [21.84, 21.77, 21.81, 21.9, 21.9, 21.87, 21.81...
1      [43.73, 42.19, 42.09, 42.09, 42.02, 41.95, 41....
2      [17.06, 17.05, 16.99, 16.96, 16.79, 16.58, 16....
3      [37.17, 37.38, 37.4, 37.36, 37.46, 37.7, 37.58...
4      [17.73, 17.64, 17.46, 17.35, 17.14, 16.99, 16....
...                                                  ...
37044  [324.56, 324.56, 324.56, 324.56, 324.56, 324.5...
37045  [39.02, 39.67, 40.05, 39.09, 38.69, 39.59, 39....
37046  [31.1, 31.44, 31.22, 31.09, 31.0, 30.84, 30.62...
37047  [20.79, 20.69, 20.59, 20.41, 20.27, 20.23, 20....
37048  [28.91, 29.14, 29.4, 29.6, 29.79, 30.08, 29.55...

                                                Itmp_seq  \
0      [26.78, 26.7, 26.55, 26.47, 26.15, 25.75, 25.6...
1      [42.02, 43.59, 44.67, 44.6, 44.43, 44.28, 44.2...
2      [17.0, 16.98, 16.84, 16.79, 16.7, 16.63, 16.57...
3      [41.37, 41.55, 41.87, 42.06, 42.3, 42.5, 42.75...
4      [18.23, 18.14, 18.02, 17.93, 18.33, 19.89, 20....
...                                                  ...
37044  [16.12, 16.13, 16.3, 16.31, 16.3, 16.3, 16.11,...
37045  [39.79, 40.3, 41.93, 41.37, 40.44, 41.48, 42.4...
37046  [37.39, 37.47, 37.48, 37.3, 37.16, 36.92, 36.7...
37047  [37.39, 37.24, 37.19, 37.09, 37.09, 37.01, 36....
37048  [29.83, 30.17, 30.42, 30.69, 31.03, 31.63, 31....

                                                Pab1_seq  \
0      [90.39, 90.39, 90.39, 90.39, 90.39, 90.39, 90....
1      [43.31, 90.39, 90.39, 90.39, 90.39, 90.39, 90....
2      [-1.99, -1.99, -1.99, -1.99, -1.99, -1.99, -1....
3      [9.35, 8.41, 4.81, 1.91, 2.17, 2.04, 1.2, 0.61...
4      [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.0...
...                                                  ...
37044  [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0...
37045  [0.07, 0.05, 0.04, 0.02, 0.01, 0.01, 0.01, 0.0...
37046  [51.17, 29.55, 0.01, 0.01, 0.01, 0.01, 0.01, 0...
37047  [0.01, 3.14, 3.09, 1.87, 3.06, 3.1, 2.92, 3.78...
37048  [90.17, 90.17, 90.17, 44.32, 1.25, 1.69, 0.98,...

                                                  target  index  TurbID  \
0      [1422.04, 1519.51, 1501.53, 1519.98, 1519.36, ...  21207      14
1      [209.79, 247.88, 371.06, 183.73, 194.71, 132.3...   9625     118
2      [80.74, 77.03, 100.68, 1.18, 0.0, 0.0, 0.0, 0....  20781     126
3      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  16070     103
4      [104.76, 96.46, 128.23, 128.2, 113.63, 85.32, ...  24026     117
...                                                  ...    ...     ...
37044  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11.42...  26081      67
37045  [448.04, 366.33, 318.85, 503.17, 327.75, 358.7...  10203     110
37046  [0.0, 0.0, 0.0, 122.54, 134.98, 64.59, 53.01, ...  15671     107
37047  [343.52, 324.64, 462.57, 798.65, 644.13, 441.4...  19585     125
37048  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 109.43, 13...   2088      84

                                              Patv_space
0      [1194.55, 1411.22, 1519.46, 1515.86, 1447.61, ...
1      [155.11, 190.08, 153.1, 197.71, 143.08, 155.7,...
2      [100.73, 86.67, 83.81, 92.14, 107.54, 117.99, ...
3      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4      [178.41, 241.21, 151.74, 0.0, 184.48, 242.99, ...
...                                                  ...
37044  [0.0, 0.0, 0.0, 143.76, 111.39, 209.05, 148.18...
37045  [445.67, 487.56, 451.39, 491.9, 568.12, 436.23...
37046  [0.0, 0.0, 0.0, 32.49, 0.0, 0.0, 0.0, 0.0, 0.0...
37047  [449.34, 276.97, 409.61, 451.46, 437.52, 451.2...
37048  [6.67, 0.0, 75.76, 0.0, 124.73, 0.0, 0.0, 0.0,...

[37049 rows x 9 columns]